version: '3.1'

services:
    redis:
        image: redis:alpine
        container_name: Nexora-redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - Nexora-net

    Nexora:
        container_name: Nexora-main
        build:
            context: .. # Build using the Dockerfile in the root directory
            dockerfile: docker/Dockerfile
        ports:
            - '${PORT}:${PORT}'
        volumes:
            # Mount local .Nexora to container's default location
            - ../.nexora:/root/.nexora
        environment:
            # --- Essential Nexora Vars ---
            - PORT=${PORT:-3000}
            - DATABASE_PATH=/root/.nexora
            - SECRETKEY_PATH=/root/.nexora
            - LOG_PATH=/root/.nexora/logs
            - BLOB_STORAGE_PATH=/root/.nexora/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=Nexora-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
        networks:
            - Nexora-net

    Nexora-worker:
        container_name: Nexora-worker
        build:
            context: .. # Build context is still the root
            dockerfile: docker/worker/Dockerfile # Ensure this path is correct
        volumes:
            # Mount same local .Nexora to worker
            - ../.nexora:/root/.nexora
        environment:
            # --- Essential Nexora Vars ---
            - WORKER_PORT=${WORKER_PORT:-5566} # Port for worker healthcheck
            - DATABASE_PATH=/root/.nexora
            - SECRETKEY_PATH=/root/.nexora
            - LOG_PATH=/root/.nexora/logs
            - BLOB_STORAGE_PATH=/root/.nexora/storage
            # --- Queue Vars (Main Instance) ---
            - MODE=queue
            - QUEUE_NAME=Nexora-queue # Ensure this matches worker
            - REDIS_URL=redis://redis:6379 # Use service name 'redis'
        depends_on:
            - redis
            - Nexora
        networks:
            - Nexora-net

volumes:
    redis_data:
        driver: local

networks:
    Nexora-net:
        driver: bridge
